import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split

np.random.seed(0)

def make_activity(center, n=100):
    return np.random.randn(n, 12) + center

walk = make_activity(0.0)
sit  = make_activity(3.0)
run  = make_activity(6.0)

X = np.vstack([walk, sit, run])
y = np.array([0]*100 + [1]*100 + [2]*100)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=1
)

model = MLPClassifier(hidden_layer_sizes=(8,), max_iter=2000, random_state=1)
model.fit(X_train, y_train)

acc = model.score(X_test, y_test)
print("Accuracy on unseen data:", round(acc * 100, 1), "%")
print("Activities: ['walk', 'sit', 'run']")

# Pull the learned weights out of the trained model
# sklearn stores weights as lists: index 0 = first layer, index 1 = second layer.
# We transpose (.T) so the shape lines up with how C++ expects W[row][col].
W1 = model.coefs_[0].T        # shape becomes (HIDDEN, FEATURES)
b1 = model.intercepts_[0]
W2 = model.coefs_[1].T        # shape becomes (CLASSES, HIDDEN)
b2 = model.intercepts_[1]

FEATURES = W1.shape[1]        # 12
HIDDEN   = W1.shape[0]        # 8
CLASSES  = W2.shape[0]        # 3

# Small helpers that turn numpy tables into C++ text 
def matrix_to_cpp(matrix):
    rows = []
    for row in matrix:
        row_text = ", ".join(f"{v:.6f}f" for v in row)
        rows.append("    { " + row_text + " }")
    return ",\n".join(rows)

def vector_to_cpp(vector):
    return ", ".join(f"{v:.6f}f" for v in vector)

# Write everything to model/weights.h 
with open("model/weights.h", "w") as f:
    f.write("// Auto-generated by train_model.py. Do not edit by hand.\n")
    f.write("#ifndef WEIGHTS_H\n#define WEIGHTS_H\n\n")
    f.write(f"const int FEATURES = {FEATURES};\n")
    f.write(f"const int HIDDEN   = {HIDDEN};\n")
    f.write(f"const int CLASSES  = {CLASSES};\n\n")

    f.write("const float W1[HIDDEN][FEATURES] = {\n")
    f.write(matrix_to_cpp(W1))
    f.write("\n};\n\n")

    f.write("const float b1[HIDDEN] = { ")
    f.write(vector_to_cpp(b1))
    f.write(" };\n\n")

    f.write("const float W2[CLASSES][HIDDEN] = {\n")
    f.write(matrix_to_cpp(W2))
    f.write("\n};\n\n")

    f.write("const float b2[CLASSES] = { ")
    f.write(vector_to_cpp(b2))
    f.write(" };\n\n")

    f.write("#endif\n")

print("Wrote model/weights.h")
